apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back
  name: back
spec:
  replicas: {{ .Values.replicaCount.back }}
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - image: "{{ .Values.image.back.repository }}:{{ .Values.image.back.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          name: back
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.appPort.back }}
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@db.{{ .Release.Namespace }}:5432/news"